// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osmand_region_info.proto

#include "osmand_region_info.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR OsmAndRegionInfo::OsmAndRegionInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.regioninfo_)*/nullptr} {}
struct OsmAndRegionInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OsmAndRegionInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OsmAndRegionInfoDefaultTypeInternal() {}
  union {
    OsmAndRegionInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OsmAndRegionInfoDefaultTypeInternal _OsmAndRegionInfo_default_instance_;
PROTOBUF_CONSTEXPR OsmAndRegions::OsmAndRegions(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.regions_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OsmAndRegionsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OsmAndRegionsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OsmAndRegionsDefaultTypeInternal() {}
  union {
    OsmAndRegions _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OsmAndRegionsDefaultTypeInternal _OsmAndRegions_default_instance_;
PROTOBUF_CONSTEXPR OsmAndRegion::OsmAndRegion(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.degx_)*/{}
  , /*decltype(_impl_._degx_cached_byte_size_)*/{0}
  , /*decltype(_impl_.degy_)*/{}
  , /*decltype(_impl_._degy_cached_byte_size_)*/{0}
  , /*decltype(_impl_.subregions_)*/{}
  , /*decltype(_impl_.continentname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct OsmAndRegionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OsmAndRegionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OsmAndRegionDefaultTypeInternal() {}
  union {
    OsmAndRegion _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OsmAndRegionDefaultTypeInternal _OsmAndRegion_default_instance_;

// ===================================================================

class OsmAndRegionInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<OsmAndRegionInfo>()._impl_._has_bits_);
  static const ::OsmAndRegions& regioninfo(const OsmAndRegionInfo* msg);
  static void set_has_regioninfo(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::OsmAndRegions&
OsmAndRegionInfo::_Internal::regioninfo(const OsmAndRegionInfo* msg) {
  return *msg->_impl_.regioninfo_;
}
OsmAndRegionInfo::OsmAndRegionInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:OsmAndRegionInfo)
}
OsmAndRegionInfo::OsmAndRegionInfo(const OsmAndRegionInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  OsmAndRegionInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.regioninfo_){nullptr}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_regioninfo()) {
    _this->_impl_.regioninfo_ = new ::OsmAndRegions(*from._impl_.regioninfo_);
  }
  // @@protoc_insertion_point(copy_constructor:OsmAndRegionInfo)
}

inline void OsmAndRegionInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.regioninfo_){nullptr}
  };
}

OsmAndRegionInfo::~OsmAndRegionInfo() {
  // @@protoc_insertion_point(destructor:OsmAndRegionInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OsmAndRegionInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.regioninfo_;
}

void OsmAndRegionInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OsmAndRegionInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:OsmAndRegionInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.regioninfo_ != nullptr);
    _impl_.regioninfo_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* OsmAndRegionInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .OsmAndRegions regionInfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_regioninfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OsmAndRegionInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OsmAndRegionInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .OsmAndRegions regionInfo = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::regioninfo(this),
        _Internal::regioninfo(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OsmAndRegionInfo)
  return target;
}

size_t OsmAndRegionInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OsmAndRegionInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .OsmAndRegions regionInfo = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.regioninfo_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OsmAndRegionInfo::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const OsmAndRegionInfo*>(
      &from));
}

void OsmAndRegionInfo::MergeFrom(const OsmAndRegionInfo& from) {
  OsmAndRegionInfo* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:OsmAndRegionInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_regioninfo()) {
    _this->_internal_mutable_regioninfo()->::OsmAndRegions::MergeFrom(
        from._internal_regioninfo());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void OsmAndRegionInfo::CopyFrom(const OsmAndRegionInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OsmAndRegionInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OsmAndRegionInfo::IsInitialized() const {
  if (_internal_has_regioninfo()) {
    if (!_impl_.regioninfo_->IsInitialized()) return false;
  }
  return true;
}

void OsmAndRegionInfo::InternalSwap(OsmAndRegionInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.regioninfo_, other->_impl_.regioninfo_);
}

std::string OsmAndRegionInfo::GetTypeName() const {
  return "OsmAndRegionInfo";
}


// ===================================================================

class OsmAndRegions::_Internal {
 public:
};

OsmAndRegions::OsmAndRegions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:OsmAndRegions)
}
OsmAndRegions::OsmAndRegions(const OsmAndRegions& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  OsmAndRegions* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.regions_){from._impl_.regions_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:OsmAndRegions)
}

inline void OsmAndRegions::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.regions_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

OsmAndRegions::~OsmAndRegions() {
  // @@protoc_insertion_point(destructor:OsmAndRegions)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OsmAndRegions::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.regions_.~RepeatedPtrField();
}

void OsmAndRegions::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OsmAndRegions::Clear() {
// @@protoc_insertion_point(message_clear_start:OsmAndRegions)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.regions_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* OsmAndRegions::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .OsmAndRegion regions = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_regions(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OsmAndRegions::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OsmAndRegions)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .OsmAndRegion regions = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_regions_size()); i < n; i++) {
    const auto& repfield = this->_internal_regions(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OsmAndRegions)
  return target;
}

size_t OsmAndRegions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OsmAndRegions)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .OsmAndRegion regions = 3;
  total_size += 1UL * this->_internal_regions_size();
  for (const auto& msg : this->_impl_.regions_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OsmAndRegions::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const OsmAndRegions*>(
      &from));
}

void OsmAndRegions::MergeFrom(const OsmAndRegions& from) {
  OsmAndRegions* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:OsmAndRegions)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.regions_.MergeFrom(from._impl_.regions_);
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void OsmAndRegions::CopyFrom(const OsmAndRegions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OsmAndRegions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OsmAndRegions::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(_impl_.regions_))
    return false;
  return true;
}

void OsmAndRegions::InternalSwap(OsmAndRegions* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.regions_.InternalSwap(&other->_impl_.regions_);
}

std::string OsmAndRegions::GetTypeName() const {
  return "OsmAndRegions";
}


// ===================================================================

class OsmAndRegion::_Internal {
 public:
  using HasBits = decltype(std::declval<OsmAndRegion>()._impl_._has_bits_);
  static void set_has_continentname(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000002) ^ 0x00000002) != 0;
  }
};

OsmAndRegion::OsmAndRegion(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:OsmAndRegion)
}
OsmAndRegion::OsmAndRegion(const OsmAndRegion& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  OsmAndRegion* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.degx_){from._impl_.degx_}
    , /*decltype(_impl_._degx_cached_byte_size_)*/{0}
    , decltype(_impl_.degy_){from._impl_.degy_}
    , /*decltype(_impl_._degy_cached_byte_size_)*/{0}
    , decltype(_impl_.subregions_){from._impl_.subregions_}
    , decltype(_impl_.continentname_){}
    , decltype(_impl_.name_){}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.continentname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.continentname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_continentname()) {
    _this->_impl_.continentname_.Set(from._internal_continentname(), 
      _this->GetArenaForAllocation());
  }
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_name()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:OsmAndRegion)
}

inline void OsmAndRegion::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.degx_){arena}
    , /*decltype(_impl_._degx_cached_byte_size_)*/{0}
    , decltype(_impl_.degy_){arena}
    , /*decltype(_impl_._degy_cached_byte_size_)*/{0}
    , decltype(_impl_.subregions_){arena}
    , decltype(_impl_.continentname_){}
    , decltype(_impl_.name_){}
  };
  _impl_.continentname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.continentname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OsmAndRegion::~OsmAndRegion() {
  // @@protoc_insertion_point(destructor:OsmAndRegion)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OsmAndRegion::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.degx_.~RepeatedField();
  _impl_.degy_.~RepeatedField();
  _impl_.subregions_.~RepeatedPtrField();
  _impl_.continentname_.Destroy();
  _impl_.name_.Destroy();
}

void OsmAndRegion::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OsmAndRegion::Clear() {
// @@protoc_insertion_point(message_clear_start:OsmAndRegion)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.degx_.Clear();
  _impl_.degy_.Clear();
  _impl_.subregions_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.continentname_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* OsmAndRegion::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string continentName = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_continentname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 degX = 4 [packed = true];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_degx(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          _internal_add_degx(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 degY = 5 [packed = true];
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_degy(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 40) {
          _internal_add_degy(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .OsmAndRegion subregions = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_subregions(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<66>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OsmAndRegion::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OsmAndRegion)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string continentName = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_continentname(), target);
  }

  // required string name = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  // repeated int32 degX = 4 [packed = true];
  {
    int byte_size = _impl_._degx_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          4, _internal_degx(), byte_size, target);
    }
  }

  // repeated int32 degY = 5 [packed = true];
  {
    int byte_size = _impl_._degy_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          5, _internal_degy(), byte_size, target);
    }
  }

  // repeated .OsmAndRegion subregions = 8;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_subregions_size()); i < n; i++) {
    const auto& repfield = this->_internal_subregions(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(8, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OsmAndRegion)
  return target;
}

size_t OsmAndRegion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OsmAndRegion)
  size_t total_size = 0;

  // required string name = 2;
  if (_internal_has_name()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 degX = 4 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.degx_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._degx_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated int32 degY = 5 [packed = true];
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.degy_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._degy_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .OsmAndRegion subregions = 8;
  total_size += 1UL * this->_internal_subregions_size();
  for (const auto& msg : this->_impl_.subregions_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional string continentName = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_continentname());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OsmAndRegion::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const OsmAndRegion*>(
      &from));
}

void OsmAndRegion::MergeFrom(const OsmAndRegion& from) {
  OsmAndRegion* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:OsmAndRegion)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.degx_.MergeFrom(from._impl_.degx_);
  _this->_impl_.degy_.MergeFrom(from._impl_.degy_);
  _this->_impl_.subregions_.MergeFrom(from._impl_.subregions_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_continentname(from._internal_continentname());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_name(from._internal_name());
    }
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void OsmAndRegion::CopyFrom(const OsmAndRegion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OsmAndRegion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OsmAndRegion::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(_impl_.subregions_))
    return false;
  return true;
}

void OsmAndRegion::InternalSwap(OsmAndRegion* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.degx_.InternalSwap(&other->_impl_.degx_);
  _impl_.degy_.InternalSwap(&other->_impl_.degy_);
  _impl_.subregions_.InternalSwap(&other->_impl_.subregions_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.continentname_, lhs_arena,
      &other->_impl_.continentname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
}

std::string OsmAndRegion::GetTypeName() const {
  return "OsmAndRegion";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::OsmAndRegionInfo*
Arena::CreateMaybeMessage< ::OsmAndRegionInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OsmAndRegionInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::OsmAndRegions*
Arena::CreateMaybeMessage< ::OsmAndRegions >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OsmAndRegions >(arena);
}
template<> PROTOBUF_NOINLINE ::OsmAndRegion*
Arena::CreateMaybeMessage< ::OsmAndRegion >(Arena* arena) {
  return Arena::CreateMessageInternal< ::OsmAndRegion >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
