// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osmand_region_info.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_osmand_5fregion_5finfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_osmand_5fregion_5finfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_osmand_5fregion_5finfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_osmand_5fregion_5finfo_2eproto {
  static const uint32_t offsets[];
};
class OsmAndRegion;
struct OsmAndRegionDefaultTypeInternal;
extern OsmAndRegionDefaultTypeInternal _OsmAndRegion_default_instance_;
class OsmAndRegionInfo;
struct OsmAndRegionInfoDefaultTypeInternal;
extern OsmAndRegionInfoDefaultTypeInternal _OsmAndRegionInfo_default_instance_;
class OsmAndRegions;
struct OsmAndRegionsDefaultTypeInternal;
extern OsmAndRegionsDefaultTypeInternal _OsmAndRegions_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::OsmAndRegion* Arena::CreateMaybeMessage<::OsmAndRegion>(Arena*);
template<> ::OsmAndRegionInfo* Arena::CreateMaybeMessage<::OsmAndRegionInfo>(Arena*);
template<> ::OsmAndRegions* Arena::CreateMaybeMessage<::OsmAndRegions>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class OsmAndRegionInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:OsmAndRegionInfo) */ {
 public:
  inline OsmAndRegionInfo() : OsmAndRegionInfo(nullptr) {}
  ~OsmAndRegionInfo() override;
  explicit PROTOBUF_CONSTEXPR OsmAndRegionInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OsmAndRegionInfo(const OsmAndRegionInfo& from);
  OsmAndRegionInfo(OsmAndRegionInfo&& from) noexcept
    : OsmAndRegionInfo() {
    *this = ::std::move(from);
  }

  inline OsmAndRegionInfo& operator=(const OsmAndRegionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline OsmAndRegionInfo& operator=(OsmAndRegionInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const OsmAndRegionInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const OsmAndRegionInfo* internal_default_instance() {
    return reinterpret_cast<const OsmAndRegionInfo*>(
               &_OsmAndRegionInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OsmAndRegionInfo& a, OsmAndRegionInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(OsmAndRegionInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OsmAndRegionInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OsmAndRegionInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OsmAndRegionInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const OsmAndRegionInfo& from);
  void MergeFrom(const OsmAndRegionInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OsmAndRegionInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "OsmAndRegionInfo";
  }
  protected:
  explicit OsmAndRegionInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionInfoFieldNumber = 1,
  };
  // optional .OsmAndRegions regionInfo = 1;
  bool has_regioninfo() const;
  private:
  bool _internal_has_regioninfo() const;
  public:
  void clear_regioninfo();
  const ::OsmAndRegions& regioninfo() const;
  PROTOBUF_NODISCARD ::OsmAndRegions* release_regioninfo();
  ::OsmAndRegions* mutable_regioninfo();
  void set_allocated_regioninfo(::OsmAndRegions* regioninfo);
  private:
  const ::OsmAndRegions& _internal_regioninfo() const;
  ::OsmAndRegions* _internal_mutable_regioninfo();
  public:
  void unsafe_arena_set_allocated_regioninfo(
      ::OsmAndRegions* regioninfo);
  ::OsmAndRegions* unsafe_arena_release_regioninfo();

  // @@protoc_insertion_point(class_scope:OsmAndRegionInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::OsmAndRegions* regioninfo_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_osmand_5fregion_5finfo_2eproto;
};
// -------------------------------------------------------------------

class OsmAndRegions final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:OsmAndRegions) */ {
 public:
  inline OsmAndRegions() : OsmAndRegions(nullptr) {}
  ~OsmAndRegions() override;
  explicit PROTOBUF_CONSTEXPR OsmAndRegions(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OsmAndRegions(const OsmAndRegions& from);
  OsmAndRegions(OsmAndRegions&& from) noexcept
    : OsmAndRegions() {
    *this = ::std::move(from);
  }

  inline OsmAndRegions& operator=(const OsmAndRegions& from) {
    CopyFrom(from);
    return *this;
  }
  inline OsmAndRegions& operator=(OsmAndRegions&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const OsmAndRegions& default_instance() {
    return *internal_default_instance();
  }
  static inline const OsmAndRegions* internal_default_instance() {
    return reinterpret_cast<const OsmAndRegions*>(
               &_OsmAndRegions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(OsmAndRegions& a, OsmAndRegions& b) {
    a.Swap(&b);
  }
  inline void Swap(OsmAndRegions* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OsmAndRegions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OsmAndRegions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OsmAndRegions>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const OsmAndRegions& from);
  void MergeFrom(const OsmAndRegions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OsmAndRegions* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "OsmAndRegions";
  }
  protected:
  explicit OsmAndRegions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionsFieldNumber = 3,
  };
  // repeated .OsmAndRegion regions = 3;
  int regions_size() const;
  private:
  int _internal_regions_size() const;
  public:
  void clear_regions();
  ::OsmAndRegion* mutable_regions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion >*
      mutable_regions();
  private:
  const ::OsmAndRegion& _internal_regions(int index) const;
  ::OsmAndRegion* _internal_add_regions();
  public:
  const ::OsmAndRegion& regions(int index) const;
  ::OsmAndRegion* add_regions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion >&
      regions() const;

  // @@protoc_insertion_point(class_scope:OsmAndRegions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion > regions_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_osmand_5fregion_5finfo_2eproto;
};
// -------------------------------------------------------------------

class OsmAndRegion final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:OsmAndRegion) */ {
 public:
  inline OsmAndRegion() : OsmAndRegion(nullptr) {}
  ~OsmAndRegion() override;
  explicit PROTOBUF_CONSTEXPR OsmAndRegion(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OsmAndRegion(const OsmAndRegion& from);
  OsmAndRegion(OsmAndRegion&& from) noexcept
    : OsmAndRegion() {
    *this = ::std::move(from);
  }

  inline OsmAndRegion& operator=(const OsmAndRegion& from) {
    CopyFrom(from);
    return *this;
  }
  inline OsmAndRegion& operator=(OsmAndRegion&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const OsmAndRegion& default_instance() {
    return *internal_default_instance();
  }
  static inline const OsmAndRegion* internal_default_instance() {
    return reinterpret_cast<const OsmAndRegion*>(
               &_OsmAndRegion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(OsmAndRegion& a, OsmAndRegion& b) {
    a.Swap(&b);
  }
  inline void Swap(OsmAndRegion* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OsmAndRegion* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OsmAndRegion* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OsmAndRegion>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const OsmAndRegion& from);
  void MergeFrom(const OsmAndRegion& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OsmAndRegion* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "OsmAndRegion";
  }
  protected:
  explicit OsmAndRegion(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDegXFieldNumber = 4,
    kDegYFieldNumber = 5,
    kSubregionsFieldNumber = 8,
    kContinentNameFieldNumber = 1,
    kNameFieldNumber = 2,
  };
  // repeated int32 degX = 4 [packed = true];
  int degx_size() const;
  private:
  int _internal_degx_size() const;
  public:
  void clear_degx();
  private:
  int32_t _internal_degx(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_degx() const;
  void _internal_add_degx(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_degx();
  public:
  int32_t degx(int index) const;
  void set_degx(int index, int32_t value);
  void add_degx(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      degx() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_degx();

  // repeated int32 degY = 5 [packed = true];
  int degy_size() const;
  private:
  int _internal_degy_size() const;
  public:
  void clear_degy();
  private:
  int32_t _internal_degy(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_degy() const;
  void _internal_add_degy(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_degy();
  public:
  int32_t degy(int index) const;
  void set_degy(int index, int32_t value);
  void add_degy(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      degy() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_degy();

  // repeated .OsmAndRegion subregions = 8;
  int subregions_size() const;
  private:
  int _internal_subregions_size() const;
  public:
  void clear_subregions();
  ::OsmAndRegion* mutable_subregions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion >*
      mutable_subregions();
  private:
  const ::OsmAndRegion& _internal_subregions(int index) const;
  ::OsmAndRegion* _internal_add_subregions();
  public:
  const ::OsmAndRegion& subregions(int index) const;
  ::OsmAndRegion* add_subregions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion >&
      subregions() const;

  // optional string continentName = 1;
  bool has_continentname() const;
  private:
  bool _internal_has_continentname() const;
  public:
  void clear_continentname();
  const std::string& continentname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_continentname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_continentname();
  PROTOBUF_NODISCARD std::string* release_continentname();
  void set_allocated_continentname(std::string* continentname);
  private:
  const std::string& _internal_continentname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_continentname(const std::string& value);
  std::string* _internal_mutable_continentname();
  public:

  // required string name = 2;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:OsmAndRegion)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > degx_;
    mutable std::atomic<int> _degx_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > degy_;
    mutable std::atomic<int> _degy_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion > subregions_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr continentname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_osmand_5fregion_5finfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OsmAndRegionInfo

// optional .OsmAndRegions regionInfo = 1;
inline bool OsmAndRegionInfo::_internal_has_regioninfo() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.regioninfo_ != nullptr);
  return value;
}
inline bool OsmAndRegionInfo::has_regioninfo() const {
  return _internal_has_regioninfo();
}
inline void OsmAndRegionInfo::clear_regioninfo() {
  if (_impl_.regioninfo_ != nullptr) _impl_.regioninfo_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::OsmAndRegions& OsmAndRegionInfo::_internal_regioninfo() const {
  const ::OsmAndRegions* p = _impl_.regioninfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::OsmAndRegions&>(
      ::_OsmAndRegions_default_instance_);
}
inline const ::OsmAndRegions& OsmAndRegionInfo::regioninfo() const {
  // @@protoc_insertion_point(field_get:OsmAndRegionInfo.regionInfo)
  return _internal_regioninfo();
}
inline void OsmAndRegionInfo::unsafe_arena_set_allocated_regioninfo(
    ::OsmAndRegions* regioninfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.regioninfo_);
  }
  _impl_.regioninfo_ = regioninfo;
  if (regioninfo) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:OsmAndRegionInfo.regionInfo)
}
inline ::OsmAndRegions* OsmAndRegionInfo::release_regioninfo() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::OsmAndRegions* temp = _impl_.regioninfo_;
  _impl_.regioninfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::OsmAndRegions* OsmAndRegionInfo::unsafe_arena_release_regioninfo() {
  // @@protoc_insertion_point(field_release:OsmAndRegionInfo.regionInfo)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::OsmAndRegions* temp = _impl_.regioninfo_;
  _impl_.regioninfo_ = nullptr;
  return temp;
}
inline ::OsmAndRegions* OsmAndRegionInfo::_internal_mutable_regioninfo() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.regioninfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::OsmAndRegions>(GetArenaForAllocation());
    _impl_.regioninfo_ = p;
  }
  return _impl_.regioninfo_;
}
inline ::OsmAndRegions* OsmAndRegionInfo::mutable_regioninfo() {
  ::OsmAndRegions* _msg = _internal_mutable_regioninfo();
  // @@protoc_insertion_point(field_mutable:OsmAndRegionInfo.regionInfo)
  return _msg;
}
inline void OsmAndRegionInfo::set_allocated_regioninfo(::OsmAndRegions* regioninfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.regioninfo_;
  }
  if (regioninfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(regioninfo);
    if (message_arena != submessage_arena) {
      regioninfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, regioninfo, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.regioninfo_ = regioninfo;
  // @@protoc_insertion_point(field_set_allocated:OsmAndRegionInfo.regionInfo)
}

// -------------------------------------------------------------------

// OsmAndRegions

// repeated .OsmAndRegion regions = 3;
inline int OsmAndRegions::_internal_regions_size() const {
  return _impl_.regions_.size();
}
inline int OsmAndRegions::regions_size() const {
  return _internal_regions_size();
}
inline void OsmAndRegions::clear_regions() {
  _impl_.regions_.Clear();
}
inline ::OsmAndRegion* OsmAndRegions::mutable_regions(int index) {
  // @@protoc_insertion_point(field_mutable:OsmAndRegions.regions)
  return _impl_.regions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion >*
OsmAndRegions::mutable_regions() {
  // @@protoc_insertion_point(field_mutable_list:OsmAndRegions.regions)
  return &_impl_.regions_;
}
inline const ::OsmAndRegion& OsmAndRegions::_internal_regions(int index) const {
  return _impl_.regions_.Get(index);
}
inline const ::OsmAndRegion& OsmAndRegions::regions(int index) const {
  // @@protoc_insertion_point(field_get:OsmAndRegions.regions)
  return _internal_regions(index);
}
inline ::OsmAndRegion* OsmAndRegions::_internal_add_regions() {
  return _impl_.regions_.Add();
}
inline ::OsmAndRegion* OsmAndRegions::add_regions() {
  ::OsmAndRegion* _add = _internal_add_regions();
  // @@protoc_insertion_point(field_add:OsmAndRegions.regions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion >&
OsmAndRegions::regions() const {
  // @@protoc_insertion_point(field_list:OsmAndRegions.regions)
  return _impl_.regions_;
}

// -------------------------------------------------------------------

// OsmAndRegion

// optional string continentName = 1;
inline bool OsmAndRegion::_internal_has_continentname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool OsmAndRegion::has_continentname() const {
  return _internal_has_continentname();
}
inline void OsmAndRegion::clear_continentname() {
  _impl_.continentname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& OsmAndRegion::continentname() const {
  // @@protoc_insertion_point(field_get:OsmAndRegion.continentName)
  return _internal_continentname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OsmAndRegion::set_continentname(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.continentname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OsmAndRegion.continentName)
}
inline std::string* OsmAndRegion::mutable_continentname() {
  std::string* _s = _internal_mutable_continentname();
  // @@protoc_insertion_point(field_mutable:OsmAndRegion.continentName)
  return _s;
}
inline const std::string& OsmAndRegion::_internal_continentname() const {
  return _impl_.continentname_.Get();
}
inline void OsmAndRegion::_internal_set_continentname(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.continentname_.Set(value, GetArenaForAllocation());
}
inline std::string* OsmAndRegion::_internal_mutable_continentname() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.continentname_.Mutable(GetArenaForAllocation());
}
inline std::string* OsmAndRegion::release_continentname() {
  // @@protoc_insertion_point(field_release:OsmAndRegion.continentName)
  if (!_internal_has_continentname()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.continentname_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.continentname_.IsDefault()) {
    _impl_.continentname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void OsmAndRegion::set_allocated_continentname(std::string* continentname) {
  if (continentname != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.continentname_.SetAllocated(continentname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.continentname_.IsDefault()) {
    _impl_.continentname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:OsmAndRegion.continentName)
}

// required string name = 2;
inline bool OsmAndRegion::_internal_has_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool OsmAndRegion::has_name() const {
  return _internal_has_name();
}
inline void OsmAndRegion::clear_name() {
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& OsmAndRegion::name() const {
  // @@protoc_insertion_point(field_get:OsmAndRegion.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OsmAndRegion::set_name(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:OsmAndRegion.name)
}
inline std::string* OsmAndRegion::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:OsmAndRegion.name)
  return _s;
}
inline const std::string& OsmAndRegion::_internal_name() const {
  return _impl_.name_.Get();
}
inline void OsmAndRegion::_internal_set_name(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* OsmAndRegion::_internal_mutable_name() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* OsmAndRegion::release_name() {
  // @@protoc_insertion_point(field_release:OsmAndRegion.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.name_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void OsmAndRegion::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:OsmAndRegion.name)
}

// repeated int32 degX = 4 [packed = true];
inline int OsmAndRegion::_internal_degx_size() const {
  return _impl_.degx_.size();
}
inline int OsmAndRegion::degx_size() const {
  return _internal_degx_size();
}
inline void OsmAndRegion::clear_degx() {
  _impl_.degx_.Clear();
}
inline int32_t OsmAndRegion::_internal_degx(int index) const {
  return _impl_.degx_.Get(index);
}
inline int32_t OsmAndRegion::degx(int index) const {
  // @@protoc_insertion_point(field_get:OsmAndRegion.degX)
  return _internal_degx(index);
}
inline void OsmAndRegion::set_degx(int index, int32_t value) {
  _impl_.degx_.Set(index, value);
  // @@protoc_insertion_point(field_set:OsmAndRegion.degX)
}
inline void OsmAndRegion::_internal_add_degx(int32_t value) {
  _impl_.degx_.Add(value);
}
inline void OsmAndRegion::add_degx(int32_t value) {
  _internal_add_degx(value);
  // @@protoc_insertion_point(field_add:OsmAndRegion.degX)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
OsmAndRegion::_internal_degx() const {
  return _impl_.degx_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
OsmAndRegion::degx() const {
  // @@protoc_insertion_point(field_list:OsmAndRegion.degX)
  return _internal_degx();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
OsmAndRegion::_internal_mutable_degx() {
  return &_impl_.degx_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
OsmAndRegion::mutable_degx() {
  // @@protoc_insertion_point(field_mutable_list:OsmAndRegion.degX)
  return _internal_mutable_degx();
}

// repeated int32 degY = 5 [packed = true];
inline int OsmAndRegion::_internal_degy_size() const {
  return _impl_.degy_.size();
}
inline int OsmAndRegion::degy_size() const {
  return _internal_degy_size();
}
inline void OsmAndRegion::clear_degy() {
  _impl_.degy_.Clear();
}
inline int32_t OsmAndRegion::_internal_degy(int index) const {
  return _impl_.degy_.Get(index);
}
inline int32_t OsmAndRegion::degy(int index) const {
  // @@protoc_insertion_point(field_get:OsmAndRegion.degY)
  return _internal_degy(index);
}
inline void OsmAndRegion::set_degy(int index, int32_t value) {
  _impl_.degy_.Set(index, value);
  // @@protoc_insertion_point(field_set:OsmAndRegion.degY)
}
inline void OsmAndRegion::_internal_add_degy(int32_t value) {
  _impl_.degy_.Add(value);
}
inline void OsmAndRegion::add_degy(int32_t value) {
  _internal_add_degy(value);
  // @@protoc_insertion_point(field_add:OsmAndRegion.degY)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
OsmAndRegion::_internal_degy() const {
  return _impl_.degy_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
OsmAndRegion::degy() const {
  // @@protoc_insertion_point(field_list:OsmAndRegion.degY)
  return _internal_degy();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
OsmAndRegion::_internal_mutable_degy() {
  return &_impl_.degy_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
OsmAndRegion::mutable_degy() {
  // @@protoc_insertion_point(field_mutable_list:OsmAndRegion.degY)
  return _internal_mutable_degy();
}

// repeated .OsmAndRegion subregions = 8;
inline int OsmAndRegion::_internal_subregions_size() const {
  return _impl_.subregions_.size();
}
inline int OsmAndRegion::subregions_size() const {
  return _internal_subregions_size();
}
inline void OsmAndRegion::clear_subregions() {
  _impl_.subregions_.Clear();
}
inline ::OsmAndRegion* OsmAndRegion::mutable_subregions(int index) {
  // @@protoc_insertion_point(field_mutable:OsmAndRegion.subregions)
  return _impl_.subregions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion >*
OsmAndRegion::mutable_subregions() {
  // @@protoc_insertion_point(field_mutable_list:OsmAndRegion.subregions)
  return &_impl_.subregions_;
}
inline const ::OsmAndRegion& OsmAndRegion::_internal_subregions(int index) const {
  return _impl_.subregions_.Get(index);
}
inline const ::OsmAndRegion& OsmAndRegion::subregions(int index) const {
  // @@protoc_insertion_point(field_get:OsmAndRegion.subregions)
  return _internal_subregions(index);
}
inline ::OsmAndRegion* OsmAndRegion::_internal_add_subregions() {
  return _impl_.subregions_.Add();
}
inline ::OsmAndRegion* OsmAndRegion::add_subregions() {
  ::OsmAndRegion* _add = _internal_add_subregions();
  // @@protoc_insertion_point(field_add:OsmAndRegion.subregions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::OsmAndRegion >&
OsmAndRegion::subregions() const {
  // @@protoc_insertion_point(field_list:OsmAndRegion.subregions)
  return _impl_.subregions_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_osmand_5fregion_5finfo_2eproto
